# Does gender affect who gets a ticket for speeding?

In [1]:
import pandas as pd

In [2]:
ri = pd.read_csv("../dataset/police.csv")
ri.head()

,state,stop_date,stop_time,county_name,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,RI,2005-01-04,12:55,NaN,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
1,RI,2005-01-23,23:15,NaN,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2,RI,2005-02-17,04:15,NaN,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
3,RI,2005-02-20,17:15,NaN,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
4,RI,2005-02-24,01:20,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3

In [5]:
female =ri[ri.driver_gender=="F"]
female.shape

(23774, 15)

In [12]:
female_and_arrested =ri[(ri.driver_gender=="F") & (ri.is_arrested == True)]
female.shape

(26183, 15)

In [13]:
female_or_arrested =ri[(ri.driver_gender=="F") | (ri.is_arrested == True)]
female.shape

(26183, 15)

## Filtering by multiple conditions

Which one of these commands would filter the ri DataFrame to only include female drivers who were stopped for a speeding violation?

In [15]:
ri[(ri.driver_gender == 'F') & (ri.violation == 'Speeding')]

,state,stop_date,stop_time,county_name,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
4,RI,2005-02-24,01:20,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3
5,RI,2005-03-14,10:00,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
8,RI,2005-07-14,11:20,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
11,RI,2005-07-18,19:30,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
13,RI,2005-07-24,20:10,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91712,RI,2015-12-30,14:09,NaN,F,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False,Zone X4
91715,RI,2015-12-30,19:21,NaN,F,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False,Zone X1
91717,RI,2015-12-30,23:26,NaN,F,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
91723,RI,2015-12-31,07:31,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X1
91737,RI,2015-12-31,21:59,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3

## Comparing speeding outcomes by gender

In [17]:
# Create a DataFrame of female drivers stopped for speeding
female_and_speeding = ri[(ri.driver_gender =='F')&(ri.violation=='Speeding')]

# Create a DataFrame of male drivers stopped for speeding
male_and_speeding = ri[(ri.driver_gender=='M')&(ri.violation=='Speeding')]


# Compute the stop outcomes for female drivers (as proportions)
print(female_and_speeding.stop_outcome.value_counts(normalize=True))
print("_________")
# Compute the stop outcomes for male drivers (as proportions)
print(male_and_speeding.stop_outcome.value_counts(normalize=True))

Citation            0.952192
Warning             0.040074
Arrest Driver       0.005752
N/D                 0.000959
Arrest Passenger    0.000639
No Action           0.000383
Name: stop_outcome, dtype: float64
_________
Citation            0.944595
Warning             0.036184
Arrest Driver       0.015895
Arrest Passenger    0.001281
No Action           0.001068
N/D                 0.000976
Name: stop_outcome, dtype: float64